import type { Compliance } from '@/types'

export const DEFAULT_COMPLIANCES: Compliance[] = [
  {
    id: 1,
    name: 'Food Business Registration',
    authority: 'Food Standards Agency / Local Council',
    category: 'Food Safety',
    frequency: 'One-time',
    description: 'Mandatory registration with your local authority at least 28 days before trading as a food business.',
    documents: ['Registration Certificate', 'EHO Inspection Report'],
    dueDate: '2026-12-31',
    status: 'Pending',
    history: [],
  },
  {
    id: 2,
    name: 'HACCP Records & Food Safety Management',
    authority: 'Food Standards Agency (EHO)',
    category: 'Food Safety',
    frequency: 'Ongoing',
    description: 'HACCP food safety management records — the first thing an EHO inspector checks. Missing records are the #1 cause of sub-3 FHRS ratings.',
    documents: ['HACCP Plan', 'Temperature Logs', 'Cleaning Schedule', 'Supplier Records'],
    dueDate: '2026-09-30',
    status: 'Pending',
    history: [],
  },
  {
    id: 3,
    name: 'Premises Licence (Alcohol)',
    authority: 'Local Authority',
    category: 'Licensing',
    frequency: 'Ongoing',
    description: 'Premises licence for sale of alcohol and late-night refreshment under the Licensing Act 2003.',
    documents: ['Premises Licence', 'DPS DBS Certificate', 'Challenge 25 Policy'],
    dueDate: '2026-10-30',
    status: 'Pending',
    history: [],
  },
]

export const ALL_LICENSES = [
  { id: 'fbd',      name: 'Food Business Registration',           authority: 'FSA / Local Council',                  category: 'Food Safety',    types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'haccp',    name: 'HACCP Records & Food Safety Mgmt',     authority: 'Food Standards Agency (EHO)',           category: 'Food Safety',    types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'allergen', name: "Allergen Management (Natasha's Law)",   authority: 'FSA / Trading Standards',              category: 'Food Safety',    types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'premises', name: 'Premises Licence (Alcohol)',            authority: 'Local Authority',                       category: 'Licensing',      types: ['restaurant', 'hotel', 'cafe'] },
  { id: 'fire',     name: 'Fire Risk Assessment',                   authority: 'Local Fire Service',                   category: 'Safety',         types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'gas',      name: 'Gas Safety Certificate (CP12)',          authority: 'Gas Safe Register / HSE',              category: 'Safety',         types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'other'] },
  { id: 'eli',      name: "Employer's Liability Insurance",         authority: 'HSE / Insurance Provider',             category: 'Legal',          types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'nlw',      name: 'National Living Wage Payroll Review',    authority: 'HMRC',                                 category: 'Labour & HR',    types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'rtw',      name: 'Right to Work Records',                  authority: 'Home Office / UKVI',                   category: 'Labour & HR',    types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'vat',      name: 'VAT Registration & MTD Returns',         authority: 'HMRC',                                 category: 'Tax',            types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'ico',      name: 'GDPR / ICO Data Protection Reg.',        authority: "Information Commissioner's Office",    category: 'Data & Privacy', types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'retail', 'other'] },
  { id: 'eicr',     name: 'Electrical Safety Certificate (EICR)',   authority: 'Local Authority / HSE',                category: 'Safety',         types: ['restaurant', 'hotel', 'cafe', 'delivery_kitchen', 'other'] },
]

export const LICENSE_DOCS: Record<string, string[]> = {
  fbd:      ['Registration Form', 'Food Safety Plan', 'Site Layout', 'Manager ID'],
  haccp:    ['HACCP Plan', 'Temperature Log Sheets', 'Cleaning Schedule', 'Supplier Records', 'Training Records'],
  allergen: ['Allergen Matrix (all 14 allergens)', 'Written Allergen Menu', 'Supplier Ingredient Declarations', 'Staff Training Certificates'],
  premises: ['Application Form', 'Operating Schedule', 'DPS DBS Certificate', 'Layout Plan', 'Notice of Application'],
  fire:     ['Fire Risk Assessment Report', 'Extinguisher Service Certificate', 'Evacuation Plan', 'Fire Detection Service Record'],
  gas:      ['CP12 Certificate', 'Gas Safe Engineer Report', 'Appliance Service Record'],
  eli:      ["Employer's Liability Insurance Certificate", 'Policy Schedule', 'Renewal Confirmation'],
  nlw:      ['Payroll Records', 'NLW Rate Review Document', 'PAYE Settlement'],
  rtw:      ['RTW Check Records', 'Passport / BRP Copies', 'EU Share Code Records'],
  vat:      ['VAT Registration Certificate', 'Quarterly VAT Returns', 'MTD Software Authorisation'],
  ico:      ['ICO Registration Certificate', 'Privacy Policy', 'Data Retention Policy'],
  eicr:     ['EICR Report', 'Electrician Certification', 'Remedial Work Records'],
}
