import type { Metadata } from 'next'
import Nav from '@/components/Nav'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy — Complynt',
  description: 'Privacy Policy for Complynt. We explain what personal data we collect, how we use it, and your rights under UK GDPR.',
}

const EFFECTIVE = '1 July 2026'
const UPDATED   = '29 July 2026'

const sections = [
  {
    title: '1. Who we are',
    body: `Complynt Ltd ("Complynt", "we", "us", "our") is the data controller for personal data processed through the Complynt platform.\n\nWe are registered with the Information Commissioner's Office (ICO) as required by UK data protection law.\n\nContact: privacy@complynt.co.uk\nAddress: United Kingdom`,
  },
  {
    title: '2. What personal data we collect',
    body: `We collect and process the following categories of personal data:\n\n• Account data: name, email address, and password (hashed) when you register\n• Business data: business name, type, city, and location details you provide during onboarding\n• Compliance data: licence information, expiry dates, document uploads, temperature logs, allergen records, and staff training records that you enter into the Service\n• Contact preferences: email address and phone number for deadline alerts\n• Usage data: how you interact with the Service, pages visited, features used, and error logs\n• Technical data: IP address, browser type, device type, and session identifiers\n• Payment data: billing details processed by our third-party payment provider (we do not store card details)`,
  },
  {
    title: '3. How we use your data',
    body: `We use your personal data for the following purposes:\n\n• Providing the Service: operating, maintaining, and personalising your compliance dashboard\n• Deadline alerts: sending reminder notifications by email or SMS when you have upcoming compliance deadlines\n• Account management: verifying your identity, managing your subscription, and communicating service updates\n• Customer support: responding to enquiries and resolving issues\n• Security: detecting and preventing fraud, abuse, and unauthorised access\n• Product improvement: analysing aggregated, anonymised usage patterns to improve features (we do not sell individual usage data)\n• Legal compliance: meeting our obligations under applicable law`,
  },
  {
    title: '4. Legal basis for processing (UK GDPR)',
    body: `We process your personal data on the following legal bases:\n\n• Contract performance: processing necessary to provide the Service you have signed up for (Art. 6(1)(b) UK GDPR)\n• Legitimate interests: security monitoring, fraud prevention, and product analytics, where these interests are not overridden by your rights (Art. 6(1)(f) UK GDPR)\n• Legal obligation: where we are required by law to process data (Art. 6(1)(c) UK GDPR)\n• Consent: for optional communications such as marketing emails, where we have obtained your explicit consent (Art. 6(1)(a) UK GDPR) — you may withdraw consent at any time`,
  },
  {
    title: '5. Data storage and security',
    body: `Your data is stored using Google Firebase (Firestore database and Firebase Storage), operated by Google LLC. Firebase servers are located in the European Economic Area (EEA) and United Kingdom by default.\n\nWe implement appropriate technical and organisational measures to protect your data, including:\n\n• Encryption in transit (TLS) and at rest\n• Firebase Security Rules that restrict data access to the account owner\n• Role-based access controls for Complynt staff\n• Regular security reviews\n\nWhile we take security seriously, no system is completely secure. If you believe your account has been compromised, please contact us immediately at privacy@complynt.co.uk.`,
  },
  {
    title: '6. Third parties we work with',
    body: `We share personal data only with the following third-party processors, and only to the extent necessary to provide the Service:\n\n• Google Firebase / Google LLC — database, file storage, and authentication\n• Anthropic — AI responses generated by our compliance assistant (query text only; no personal identifiers are sent)\n• Stripe (or equivalent) — payment processing for paid subscriptions\n• Email delivery provider — sending deadline alert and account emails\n\nAll third-party processors are bound by data processing agreements and are required to handle data in accordance with UK GDPR. We do not sell, rent, or trade your personal data to third parties for their own marketing purposes.`,
  },
  {
    title: '7. International data transfers',
    body: `Some of our processors (including Google and Anthropic) are based in the United States. Where personal data is transferred outside the UK, we ensure appropriate safeguards are in place, such as:\n\n• UK International Data Transfer Agreements (IDTAs)\n• Standard Contractual Clauses approved by the ICO\n• Adequacy decisions where applicable\n\nYou can request details of the specific transfer mechanisms we rely on by contacting us at privacy@complynt.co.uk.`,
  },
  {
    title: '8. Data retention',
    body: `We retain your personal data for as long as your account is active, plus the following periods after closure:\n\n• Account and compliance data: deleted within 30 days of account closure\n• Uploaded documents: deleted within 30 days of account closure\n• Payment records: retained for 7 years as required by HMRC for tax purposes\n• Anonymised analytics data: retained indefinitely in aggregated, non-identifiable form\n\nYou may request early deletion of your data at any time (see Section 9).`,
  },
  {
    title: '9. Your rights',
    body: `Under UK GDPR, you have the following rights regarding your personal data:\n\n• Right of access: request a copy of the personal data we hold about you\n• Right to rectification: request correction of inaccurate or incomplete data\n• Right to erasure: request deletion of your data ("right to be forgotten") where no legal basis for retention exists\n• Right to restrict processing: request that we limit how we use your data in certain circumstances\n• Right to data portability: receive your data in a structured, machine-readable format\n• Right to object: object to processing based on legitimate interests or for direct marketing\n• Rights related to automated decision-making: we do not make solely automated decisions with legal or significant effects on you\n\nTo exercise any of these rights, please contact privacy@complynt.co.uk. We will respond within 30 days. We may need to verify your identity before processing your request.`,
  },
  {
    title: '10. Cookies',
    body: `We use the following types of cookies and similar technologies:\n\n• Essential cookies: required to operate the Service (authentication session tokens, security)\n• Analytics cookies: to understand how the Service is used in aggregate (we use privacy-friendly analytics with no cross-site tracking)\n\nWe do not use advertising or tracking cookies. You can control cookies via your browser settings, but disabling essential cookies will prevent the Service from functioning correctly.`,
  },
  {
    title: '11. Children',
    body: `The Service is not directed at children under 18 years of age. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, please contact us and we will delete it promptly.`,
  },
  {
    title: '12. Changes to this policy',
    body: `We may update this Privacy Policy from time to time to reflect changes in our practices or applicable law. We will notify you of material changes by email or by displaying a notice within the Service at least 14 days before the changes take effect.\n\nYour continued use of the Service after the effective date of the revised Privacy Policy constitutes acceptance of those changes.`,
  },
  {
    title: '13. Complaints and contact',
    body: `If you have questions, concerns, or complaints about how we handle your personal data, please contact us:\n\nEmail: privacy@complynt.co.uk\nSubject line: "Privacy enquiry"\n\nIf you are not satisfied with our response, you have the right to lodge a complaint with the Information Commissioner's Office (ICO):\n\nInformation Commissioner's Office\nWycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF\nWebsite: ico.org.uk\nHelpline: 0303 123 1113`,
  },
]

export default function PrivacyPage() {
  return (
    <>
      <Nav solid />
      <main style={{ paddingTop: 'var(--nav-h)', background: '#f5f5f7', minHeight: '100vh' }}>

        {/* Hero */}
        <div style={{ background: 'white', borderBottom: '1px solid #e5e5ea', padding: '48px 24px 40px' }}>
          <div style={{ maxWidth: 760, margin: '0 auto' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: '#e8f2ff', border: '1px solid #c8dfff', borderRadius: 20, padding: '4px 12px', marginBottom: 16 }}>
              <span style={{ fontSize: 11, fontWeight: 700, color: '#0058b0', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Legal</span>
            </div>
            <h1 style={{ fontSize: 'clamp(26px, 3vw, 36px)', fontWeight: 800, color: '#1d1d1f', margin: '0 0 10px', letterSpacing: '-0.02em' }}>
              Privacy Policy
            </h1>
            <p style={{ fontSize: 14, color: '#a1a1a6', margin: '0 0 18px' }}>
              Effective {EFFECTIVE} · Last updated {UPDATED}
            </p>
            <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
              {[
                { label: 'UK GDPR compliant', color: '#1a7a34', bg: '#f0faf3', border: '#b8e6c8' },
                { label: 'No data selling',   color: '#0058b0', bg: '#e8f2ff', border: '#c8dfff' },
                { label: 'ICO registered',    color: '#7a4400', bg: '#fff8e8', border: '#ffd6a0' },
              ].map(b => (
                <span key={b.label} style={{ fontSize: 12, fontWeight: 600, color: b.color, background: b.bg, border: `1px solid ${b.border}`, padding: '4px 12px', borderRadius: 20 }}>{b.label}</span>
              ))}
            </div>
          </div>
        </div>

        {/* Content */}
        <div style={{ maxWidth: 760, margin: '0 auto', padding: '40px 24px 80px' }}>

          {/* Plain-English summary */}
          <div style={{ background: '#f0faf3', border: '1px solid #b8e6c8', borderRadius: 14, padding: '20px 24px', marginBottom: 36 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#1a7a34', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 10 }}>Plain-English summary</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                'We collect your name, email, and business details to run your account.',
                'Your compliance data belongs to you — we never sell it or use it for ads.',
                'Data is stored securely on Google Firebase in the EEA/UK.',
                'You can delete your account and all data at any time.',
                'We send deadline reminders only — no spam.',
              ].map(line => (
                <div key={line} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#1a7a34" strokeWidth="2.5" strokeLinecap="round" style={{ flexShrink: 0, marginTop: 2 }}><polyline points="20,6 9,17 4,12"/></svg>
                  <span style={{ fontSize: 14, color: '#1a7a34', lineHeight: 1.5 }}>{line}</span>
                </div>
              ))}
            </div>
          </div>

          {sections.map(s => (
            <div key={s.title} style={{ marginBottom: 36 }}>
              <h2 style={{ fontSize: 17, fontWeight: 700, color: '#1d1d1f', margin: '0 0 12px', letterSpacing: '-0.01em' }}>{s.title}</h2>
              <div style={{ background: 'white', border: '1px solid #e5e5ea', borderRadius: 14, padding: '20px 24px' }}>
                {s.body.split('\n').map((line, i) => {
                  if (!line.trim()) return <div key={i} style={{ height: 10 }} />
                  if (line.startsWith('•')) {
                    return (
                      <div key={i} style={{ display: 'flex', gap: 10, marginBottom: 6 }}>
                        <span style={{ color: '#0071e3', fontWeight: 700, flexShrink: 0, marginTop: 1 }}>•</span>
                        <p style={{ fontSize: 14, color: '#1d1d1f', lineHeight: 1.65, margin: 0 }}>{line.slice(1).trim()}</p>
                      </div>
                    )
                  }
                  return <p key={i} style={{ fontSize: 14, color: '#1d1d1f', lineHeight: 1.65, margin: '0 0 8px' }}>{line}</p>
                })}
              </div>
            </div>
          ))}

          {/* Your rights quick reference */}
          <div style={{ background: '#e8f2ff', border: '1px solid #c8dfff', borderRadius: 14, padding: '20px 24px', marginBottom: 36 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#0058b0', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 14 }}>Exercise your rights</div>
            <p style={{ fontSize: 14, color: '#0058b0', lineHeight: 1.65, margin: '0 0 14px' }}>
              To access, correct, export, or delete your data — or to withdraw consent — email us at:
            </p>
            <div style={{ background: 'white', borderRadius: 10, padding: '12px 16px', display: 'inline-block' }}>
              <span style={{ fontSize: 14, fontWeight: 700, color: '#0071e3' }}>privacy@complynt.co.uk</span>
            </div>
            <p style={{ fontSize: 13, color: '#0058b0', margin: '12px 0 0' }}>We aim to respond within 30 days, as required by UK GDPR.</p>
          </div>

          {/* Footer links */}
          <div style={{ borderTop: '1px solid #e5e5ea', paddingTop: 24, display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <Link href="/terms"   style={{ fontSize: 14, color: '#0071e3', textDecoration: 'none', fontWeight: 500 }}>Terms of Service →</Link>
            <Link href="/contact" style={{ fontSize: 14, color: '#0071e3', textDecoration: 'none', fontWeight: 500 }}>Contact us →</Link>
          </div>
        </div>

      </main>
    </>
  )
}
